name: Github Pages Deploy
on:
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'onelandworld/oneland-docs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node v16
        uses: actions/setup-node@v1
        with:
          node-version: v16.16.0

      - name: Install dependencies
        run: yarn install

      - name: Build for production
        run: yarn build

      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: docs.oneland.world
